export const DATA2024c = [
    {
        team: 0, // Blue
        names: ['Bousquet', 'Brossier'],
        id: 'f-24-1_1',
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        drive0: 0,
        drive1: 0,
        drive0Par3: 0,
        drive1Par3: 0,
        totalScore: 0,
        adjustScore: -2,
    },
    {
        team: 1, // White
        names: ['Dubé', 'Harvey'],
        id: 'f-24-2_1',
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        drive0Par3: 0,
        drive1Par3: 0,
        drive0: 0,
        drive1: 0,
        totalScore: 0,
        adjustScore: 0,
    },
    {
        team: 1,
        names: ['Bolduc', 'Gélinas'],
        id: 'f-24-3_2',
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        drive0Par3: 0,
        drive1Par3: 0,
        drive0: 0,
        drive1: 0,
        totalScore: 0,
        adjustScore: 0,
    },
    {
        team: 0, // Blue
        names: ['Gosselin', 'Paré'],
        id: 'f-24-4_2',
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        drive0Par3: 0,
        drive1Par3: 0,
        drive0: 0,
        drive1: 0,
        totalScore: 0,
        adjustScore: -2,
    },
    {
        team: 0, // Blue
        names: ['Samson', 'Beaudry'],
        id: 'f-24-5_3',
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        drive0Par3: 0,
        drive1Par3: 0,
        drive0: 0,
        drive1: 0,
        totalScore: 0,
        adjustScore: -2,
    },
    {
        team: 1, // White
        names: ['Ferland', 'Bouthillier'],
        id: 'f-24-6_3',
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        drive0Par3: 0,
        drive1Par3: 0,
        drive0: 0,
        drive1: 0,
        totalScore: 0,
        adjustScore: 0,
    },
    {
        team: 0, // Blue
        names: ['Beaudry', 'Brossier'],
        id: 's-24-1_1',
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        drive0Par3: 0,
        drive1Par3: 0,
        drive0: 0,
        drive1: 0,
        totalScore: 0,
        adjustScore: 0,
    },
    {
        team: 1, // White
        names: ['Bouthillier', 'Gélinas'],
        id: 's-24-2_1',
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        drive0Par3: 0,
        drive1Par3: 0,
        drive0: 0,
        drive1: 0,
        totalScore: 0,
        adjustScore: -2,
    },
    {
        team: 0,
        names: ['Bousquet', 'Paré'],
        id: 's-24-3_2',
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        drive0Par3: 0,
        drive1Par3: 0,
        drive0: 0,
        drive1: 0,
        totalScore: 0,
        adjustScore: 0,
    },
    {
        team: 1,
        names: ['Ferland', 'Harvey'],
        id: 's-24-4_2',
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        drive0Par3: 0,
        drive1Par3: 0,
        drive0: 0,
        drive1: 0,
        totalScore: 0,
        adjustScore: -2,
    },
    {
        team: 1,
        names: ['Dubé', 'Bolduc'],
        id: 's-24-5_3',
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        drive0Par3: 0,
        drive1Par3: 0,
        drive0: 0,
        drive1: 0,
        totalScore: 0,
        adjustScore: 0,
    },
    {
        team: 0,
        names: ['Gosselin', 'Samson'],
        id: 's-24-6_3',
        drive0: 0,
        drive0Par3: 0,
        drive1Par3: 0,
        drive1: 0,
        totalScore: 0,
        stats: Array.from({ length: 18 }, () => ({
            hole: 0,
            drive: null,
            fairway: false,
            hazard: false,
            putt: null,
            score: null,
        })),
        adjustScore: -8,
    },
];
